### Grupo 4
### Test API redmine
@key = gT1_gRupo04
### List issues
//Se tiene que pasar las credenciales a base64(GTI_Grupo_4:gT1_gRupo04)
GET https://npr3s.com/control/projects/gti-1265-1167/issues.xml
Authorization: Basic R1RJX0dydXBvXzQ6Z1QxX2dSdXBvMDQ=


###Prueba de POST - agregar nuevo issue
POST https://npr3s.com/control/projects/gti-1265-1167/issues.json
Content-Type: application/json
Authorization: Basic R1RJX0dydXBvXzQ6Z1QxX2dSdXBvMDQ=

{
    "issue": {
        "project_id": 19,
        "tracker_id": 1,
        "status_id": 1,
        "priority_id": 1,
        "subject": "Prueba POST Rest Client - Grupo4",
        "description": "Prueba simple de comando POST",
        "start_date": "2023-06-18"
    }
}

### Obtener datos de Issue creado 
GET https://npr3s.com/control/projects/gti-1265-1167/issues.xml?issue_id=234
Authorization: Basic R1RJX0dydXBvXzQ6Z1QxX2dSdXBvMDQ=